projects:
  - name: WTA
    apiId: <amplitude project api username>
    apiKey: <amplitude project api password>
    charts:
      - id: xxxxxxxx
        labels: ["sre"]
        subsystem: socket
        name: error
      - id: yyyyyyy
        labels: ["sre"]
        subsystem: socket2
        name: error