projects:
  - name: WTA
    apiId: <amplitude project api username>
    apiKey: <amplitude project api password>
    charts:
      - id: xxxxxxxx
        subsystem: socket
        name: error
      - id: yyyyyyy
        subsystem: zzz
        name: availability
        type: gauge # counter by default
        offset: 4 # take last - offset point, 0 by default